
CREATE DATABASE trackingDB;
-- drop schema public cascade;
-- create schema public;

CREATE TABLE SITES(
   SITE_ID        SERIAL PRIMARY KEY NOT NULL,
   NAME           TEXT   UNIQUE      NOT NULL,
   ADDRESS        CHAR(500)
);

CREATE INDEX SITES_IDX_SITE_ID on SITES (SITE_ID);
CREATE INDEX SITES_IDX_NAME    on SITES (NAME);
COMMENT ON TABLE SITES IS 'Store all the sites';

CREATE TABLE DEALS(
   DEAL_ID        SERIAL PRIMARY KEY       NOT NULL,
   VALUE          CHAR(15)                 NOT NULL,
   SET_BY         CHAR(500)                NOT NULL,
   CREATED_ON     TIMESTAMP WITH TIME ZONE NOT NULL
);
COMMENT ON TABLE  DEALS            IS 'Store all the deals';
COMMENT ON COLUMN DEALS.SET_BY     IS 'The name of the person who set the deal';
COMMENT ON COLUMN DEALS.CREATED_ON IS 'Setup time of the deal';

CREATE INDEX DEALS_IDX_DEAL_ID    on DEALS (DEAL_ID);
CREATE INDEX DEALS_IDX_VALUE      on DEALS (VALUE);
CREATE INDEX DEALS_IDX_CREATED_ON on DEALS (CREATED_ON);


CREATE TABLE BRANDS (
  BRANDS_ID      SERIAL    PRIMARY KEY NOT NULL,
  SITE_ID        SERIAL                NOT NULL,
  NAME           CHAR(50),
  URL            CHAR(50),
  COMMENT        TEXT,
  CONSTRAINT SITE_FKEY FOREIGN KEY (SITE_ID)
  REFERENCES SITES MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE INDEX BRANDS_IDX_BRANDS_ID on BRANDS (BRANDS_ID);
CREATE INDEX BRANDS_IDX_SITE_ID   on BRANDS (SITE_ID);
CREATE INDEX BRANDS_IDX_NAME      on BRANDS (NAME);



CREATE TABLE ACTIONS (
  ACTION_ID      SERIAL       PRIMARY KEY NOT NULL,
  BRANDS_ID      SERIAL                   NOT NULL,
  DEAL_ID        SERIAL                   NOT NULL,
  CREATED_ON     TIMESTAMP WITH TIME ZONE NOT NULL,
  ACTION_TYPE    CHAR(30),
  GCLID          CHAR(110), -- See: http://googleadsdeveloper.blogspot.co.il/2014/02/changes-to-gclid-field-length-in.html
  CONSTRAINT BRAND_FKEY FOREIGN KEY (BRANDS_ID)
  REFERENCES BRANDS MATCH SIMPLE  ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT DEAL_FKEY FOREIGN KEY (DEAL_ID)
  REFERENCES DEALS MATCH SIMPLE  ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX ACTIONS_IDX_ACTION_ID   ON ACTIONS (ACTION_ID);
CREATE INDEX ACTIONS_IDX_BRANDS_ID   ON ACTIONS (BRANDS_ID);
CREATE INDEX ACTIONS_IDX_DEAL_ID     ON ACTIONS (DEAL_ID);
CREATE INDEX ACTIONS_IDX_CREATED_ON  ON ACTIONS (CREATED_ON);
CREATE INDEX ACTIONS_IDX_ACTION_TYPE ON ACTIONS (ACTION_TYPE);
