
-- Store all the sites
CREATE TABLE SITES(
   SITE_ID        SERIAL PRIMARY KEY NOT NULL,
   NAME           TEXT   UNIQUE      NOT NULL,
   ADDRESS        CHAR(500)
);

CREATE INDEX SITE_ID on SITES (SITES);
CREATE INDEX NAME    on SITES (NAME);

-- Store all the deals
CREATE TABLE DEALS(
   DEAL_ID        SERIAL PRIMARY KEY NOT NULL,
   VALUE          CHAR(15)           NOT NULL,
   SET_BY         CHAR(500)          NOT NULL, -- The name of the person who set the deal
   CREATED_ON     TIMESTAMP          NOT NULL  -- Setup time of the deal
);

CREATE INDEX DEAL_ID on DEALS (DEAL_ID);


CREATE TABLE BRANDS (
  BRANDS_ID      SERIAL    PRIMARY KEY NOT NULL,
  SITE_ID        SERIAL                NOT NULL,
  NAME           CHAR(50),
  URL            CHAR(50),
  COMMENT        TEXT
  CONSTRAINT SITE_FKEY FOREIGN KEY (SITE_ID)
  REFERENCES SITES(SITE_ID) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX BRANDS_ID on BRANDS (BRANDS_ID);
CREATE INDEX SITE_ID   on BRANDS (SITE_ID);
CREATE INDEX NAME      on BRANDS (NAME);



CREATE TABLE ACTIONS(
  ACTION_ID      SERIAL       PRIMARY KEY NOT NULL,
  BRANDS_ID      SERIAL                   NOT NULL,
  DEAL_ID        SERIAL                   NOT NULL,
  CREATED_ON     TIMESTAMP                NOT NULL,
  ACTION_TYPE    CHAR(30),
  GCLID          CHAR(110), -- See: http://googleadsdeveloper.blogspot.co.il/2014/02/changes-to-gclid-field-length-in.html
  CONSTRAINT SITE_FKEY FOREIGN KEY (SITE_ID)
  REFERENCES SITES(SITE_ID) MATCH SIMPLE  ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX ACTION_ID   on ACTIONS (ACTION_ID);
CREATE INDEX BRANDS_ID   on ACTIONS (BRANDS_ID);
CREATE INDEX DEAL_ID     on ACTIONS (DEAL_ID);
CREATE INDEX CREATED_ON  on ACTIONS (CREATED_ON);
CREATE INDEX ACTION_TYPE on ACTIONS (ACTION_TYPE);
